### PR TITLE
Safe replace insecure HTTP links with HTTPS

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by lex111** [comment]
http://www.audiencehero.org/ seems not work anymore.

**Comment by lex111** [comment]
https://github.com/SocieteNumerique/pass-numerique can be replace with https://passnum.societenumerique.gouv.fr/ ?

**Comment by lex111** [comment]
En Marche is open source, isn't it?

**Comment by lex111** [comment]
http://hohey.fr/ now this is generally different site (_potentially dangerous_).

**Comment by dunglas** [comment]
Thanks Alexey! I made some subsequent changes in 427e33ce13533dfda15ae14e458c464721ea75ee:

* Move Le Parti de Gauche and En Marche in the open source section (because they are)
* Replace the link of the website to the GitHub/GitLab repo when the website isn't about the software itself (Mobicoop). So I think we should keep PassNum as is (the GitHub repo is more relevant for API Platform users).
* Replace the link to the GitHub repo when the website isn't in english (CoopCycle)
* Replace broken link: AudienceHero
* Remove closed company (HoHey)

Thanks for the hints!

**Comment by lex111** [comment]
I'm glad I could help. :smiley:

**Pull request merged**
