### PR TITLE
[WIP] Allow unlimited docs hierarchy

### PR DESCRIPTION
**Pull request by Fabious**
| Q             | A
| ------------- | ---
| Bug fix?      | no 
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no

Goal of this feature : allow any levels in the documentation hierarchy (a main category can have as many sub category as it wants)

To achieve that we need to work on 2 main things :
- generate recursively the actual nav.yml (bin/generate-nav)
- rework the sidebar component to also be generated recursively

Did a bit of refactoring as it was also necessary

### CODE REVIEW

**Comment by teohhanhui** [comment]
Is this really a good idea for DX?

**Comment by Fabious** [comment]
No it's not... i'm against it xD
I checked documentations of most popular frameworks and the maximum depth was 3. (like the actual api-platform doc)
Adding a level of depth is not good UX wise (i did it for learning purpose and because we asked me xD)

**Comment by alanpoulain** [comment]
I think a better way to organize the documentation would be to add the possibility to add section titles (without a new level).
We could follow what was proposed here: https://github.com/api-platform/docs/issues/884 without losing the UX.
WDYT?

**Comment by Fabious** [comment]
Due to my lack of knowledge of api-platform i can't help on the reorganization of the documentation. (Benoit did have this knowledge)

But i can suggest that if indeed we need to simplify the doc, it needs a more thoughtful work. Maybe looking to others doc ? (i see a lot of "zero" section which is a tutorial for example)

Just avoid going too deep in the hierarchy ! :)

**Pull request closed without merging**
