### PR TITLE
Add plugin for zooming images

### PR DESCRIPTION
**Pull request by lex111**
See more at https://github.com/francoischalifour/medium-zoom

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @lex111

**Comment by alanpoulain** [comment]
Is it really useful? Are we using some images which need to zoom?

Moreover it creates some issues, like with the SymfonyCasts images.

**Comment by dunglas** [comment]
I like the effect, but indeed it should be disabled when there is a link on the image (as for the SymfonyCasts player), and it breaks the SymfonyCasts image here https://api-platform.com/docs/distribution/#screencasts

Reverting for now

**Comment by lex111** [comment]
It's a pity, because the documentation has a lot of screenshots and this change is really useful! Perhaps we can make sure that SC images are not zoomed..

**Comment by dunglas** [comment]
They aren't (AFAIK)? Would you mind checking how we can fix that?

**Comment by lex111** [comment]
We can just take the code of this plugin and create our own plugin based on it. I think this is the easiest way. How's that sound?

**Comment by dunglas** [comment]
Yes sounds good. We could also add a new option (to ignore a class or something) in the original plugin?

**Comment by lex111** [comment]
Hmm, I don’t know, the author doesn’t particularly support your plugin, but I will try!

**Comment by lex111** [comment]
I mean, this is a rather specific case, and the author may reject such a change.

**Comment by alanpoulain** [comment]
I don't like the idea of having to fork (and possibly maintain) a plugin. @dunglas's proposal seems the best solution for me.

**Comment by dunglas** [comment]
It's a tiny plugin isn't it? Copy/adapt is probably the best option here if it's not thousands of lines of code.

**Comment by alanpoulain** [comment]
I would not call it tiny: https://github.com/francoischalifour/medium-zoom/blob/master/src/medium-zoom.js

**Comment by lex111** [comment]
Hey guys, I created PR, I hope the author will accept it. 
https://github.com/JaeYeopHan/gatsby-remark-images-medium-zoom/pull/5

**Comment by alanpoulain** [comment]
Nice!

**Pull request merged**
